name: Alpine (extended)

images:
  # Alpine + Hugo extended
  ext-alpine:
    target: ext-alpine
    edge: true
    alias:
      - $(VERSION)-ext-alpine
    tests:
      - hugo
      - golang
      - yarn
      - postcss
    platforms:
      - linux/amd64

  # Alpine + Hugo extended + CI
  ext-alpine-ci:
    target: ext-alpine--ci
    edge: true
    alias:
      - $(VERSION)-ext-alpine-ci
    platforms:
      - linux/amd64

  # Alpine + Hugo extended + Onbuild
  ext-alpine-onbuild:
    target: ext-alpine--onbuild
    edge: true
    alias:
      - $(VERSION)-ext-alpine-onbuild
    platforms:
      - linux/amd64

  # Alpine + Hugo extended + Asciidoctor
  ext-asciidoctor:
    target: ext-asciidoctor
    alias:
      - $(VERSION)-ext-asciidoctor
    tests:
      - hugo
      - asciidoctor
      - golang
      - yarn
      - postcss
    platforms:
      - linux/amd64

  # Alpine + Hugo extended + Asciidoctor + CI
  ext-asciidoctor-ci:
    target: ext-asciidoctor--ci
    alias:
      - $(VERSION)-ext-asciidoctor-ci
    platforms:
      - linux/amd64

  # Alpine + Hugo extended + Asciidoctor + Onbuild
  ext-asciidoctor-onbuild:
    target: ext-asciidoctor--onbuild
    alias:
      - $(VERSION)-ext-asciidoctor-onbuild
    platforms:
      - linux/amd64

  # Alpine + Hugo extended + Pandoc
  ext-pandoc:
    target: ext-pandoc
    alias:
      - $(VERSION)-ext-pandoc
    tests:
      - hugo
      - pandoc
      - golang
      - yarn
      - postcss
      - rst2html
    platforms:
      - linux/amd64

  # Alpine + Hugo extended + Pandoc + CI
  ext-pandoc-ci:
    target: ext-pandoc--ci
    alias:
      - $(VERSION)-ext-pandoc-ci
    platforms:
      - linux/amd64

  # Alpine + Hugo extended + Pandoc + Onbuild
  ext-pandoc-onbuild:
    target: ext-pandoc--onbuild
    alias:
      - $(VERSION)-ext-pandoc-onbuild
    platforms:
      - linux/amd64

tests:
  hugo:
    command: version
    expected: Hugo

  node:
    entrypoint: node
    command: --version

  asciidoctor:
    entrypoint: asciidoctor
    command: --version
    expected: Asciidoctor 2

  pandoc:
    entrypoint: pandoc-default
    command: --version
    expected: Compiled with pandoc

  golang:
    entrypoint: go
    command: version
    expected: go version

  yarn:
    entrypoint: yarn
    command: --version

  postcss:
    entrypoint: postcss
    command: --version

  rst2html:
    entrypoint: rst2html.py
    command: --version