name: Alpine (standard)

images:
  # Alpine + Hugo
  alpine:
    target: alpine
    edge: true
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    alias:
      - $(VERSION)-alpine
    tests:
      - hugo

  # Alpine + Hugo + CI
  alpine-ci:
    target: alpine--ci
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    alias:
      - $(VERSION)-alpine-ci

  # Alpine + Hugo + Onbuild
  alpine-onbuild:
    target: alpine--onbuild
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    alias:
      - $(VERSION)-alpine-onbuild

  # Alpine + Hugo + Asciidoctor
  asciidoctor:
    target: asciidoctor
    edge: true
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    alias:
      - "$(VERSION)-asciidoctor"
    tests:
      - hugo
      - asciidoctor

  # Alpine + Hugo + Asciidoctor + CI
  asciidoctor-ci:
    target: asciidoctor--ci
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    alias:
      - "$(VERSION)-asciidoctor-ci"

  # Alpine + Hugo + Asciidoctor + Onbuild
  asciidoctor-onbuild:
    target: asciidoctor--onbuild
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    alias:
      - "$(VERSION)-asciidoctor-onbuild"

  # Alpine + Hugo + Pandoc
  pandoc:
    target: pandoc
    edge: true
    platforms:
      - linux/amd64
      - linux/arm64
    alias:
      - $(VERSION)-pandoc
    tests:
      - hugo
      - pandoc

  # Alpine + Hugo + Pandoc + CI
  pandoc-ci:
    target: pandoc--ci
    platforms:
      - linux/amd64
      - linux/arm64
    alias:
      - $(VERSION)-pandoc-ci

  # Alpine + Hugo + Pandoc + Onbuild
  pandoc-onbuild:
    target: pandoc--onbuild
    platforms:
      - linux/amd64
      - linux/arm64
    alias:
      - $(VERSION)-pandoc-onbuild

tests:
  hugo:
    command: version
    expected: hugo

  asciidoctor:
    entrypoint: asciidoctor
    command: --version
    expected: Asciidoctor 2

  pandoc:
    entrypoint: pandoc
    command: --version
    expected: Compiled with pandoc
