name: Busybox (standard)

images:
  # Busybox + Hugo
  busybox:
    target: busybox
    edge: true
    platforms:
      - linux/amd64
      - linux/arm64
    alias:
      - latest
      - $(VERSION)
      - $(VERSION)-busybox
    tests:
      - hugo

  # Busybox + Hugo + CI
  busybox-ci:
    target: busybox--ci
    platforms:
      - linux/amd64
      - linux/arm64
    alias:
      - $(VERSION)-busybox-ci
      - $(VERSION)-ci
      - ci

  # Busybox + Hugo + Onbuild
  busybox-onbuild:
    target: busybox--onbuild
    platforms:
      - linux/amd64
      - linux/arm64
    alias:
      - $(VERSION)-busybox-onbuild
      - $(VERSION)-onbuild
      - onbuild

tests:
  hugo:
    command: version
    expected: hugo
