name: Debian (extended)

images:
  # Debian + Hugo extended
  ext-debian:
    target: ext-debian
    edge: true
    alias:
      - ext
      - latest-ext
      - $(VERSION)-ext
      - $(VERSION)-ext-debian
    tests:
      - hugo
      - node
      - asciidoctor
      - pandoc
      - golang
      - yarn
      - postcss
      - rst2html
    platforms:
      - linux/amd64
      - linux/arm64

  # Debian + Hugo extended + CI
  ext-debian-ci:
    target: ext-debian--ci
    alias:
      - $(VERSION)-ext-debian-ci
      - $(VERSION)-ext-ci
      - ext-ci
    platforms:
      - linux/amd64
      - linux/arm64

  # Debian + Hugo extended + Onbuild
  ext-debian-onbuild:
    target: ext-debian--onbuild
    alias:
      - $(VERSION)-ext-debian-onbuild
      - $(VERSION)-ext-onbuild
      - ext-onbuild
    platforms:
      - linux/amd64
      - linux/arm64

tests:
  hugo:
    command: version
    expected: hugo

  node:
    entrypoint: node
    command: --version

  asciidoctor:
    entrypoint: asciidoctor
    command: --version
    expected: Asciidoctor 2

  pandoc:
    entrypoint: pandoc
    command: --version
    expected: Compiled with pandoc

  golang:
    entrypoint: go
    command: version
    expected: go version

  yarn:
    entrypoint: yarn
    command: --version

  postcss:
    entrypoint: postcss
    command: --version

  rst2html:
    entrypoint: rst2html.py
    command: --version