name: Ubuntu (extended)

images:
  # Ubuntu + Hugo extended
  ext-ubuntu:
    target: ext-ubuntu
    edge: true
    alias:
      - $(VERSION)-ext-ubuntu
    tests:
      - hugo
      - node
      - asciidoctor
      - pandoc
      - golang
      - yarn
      - postcss
      - rst2html
    platforms:
      - linux/amd64
      - linux/arm64

  # Ubuntu + Hugo extended + CI
  ext-ubuntu-ci:
    target: ext-ubuntu--ci
    alias:
      - $(VERSION)-ext-ubuntu-ci
    platforms:
      - linux/amd64
      - linux/arm64

  # Ubuntu + Hugo extended + Onbuild
  ext-ubuntu-onbuild:
    target: ext-ubuntu--onbuild
    alias:
      - $(VERSION)-ext-ubuntu-onbuild
    platforms:
      - linux/amd64
      - linux/arm64

tests:
  hugo:
    command: version
    expected: hugo

  node:
    entrypoint: node
    command: --version

  asciidoctor:
    entrypoint: asciidoctor
    command: --version
    expected: Asciidoctor 2

  pandoc:
    entrypoint: pandoc
    command: --version
    expected: Compiled with pandoc

  golang:
    entrypoint: go
    command: version
    expected: go version

  yarn:
    entrypoint: yarn
    command: --version

  postcss:
    entrypoint: postcss
    command: --version

  rst2html:
    entrypoint: rst2html.py
    command: --version