name: Ubuntu (standard)

images:
  # Ubuntu + Hugo
  ubuntu:
    target: ubuntu
    edge: true
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    alias:
      - $(VERSION)-ubuntu
    tests:
      - hugo

  # Ubuntu + Hugo + CI
  ubuntu-ci:
    target: ubuntu--ci
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    alias:
      - $(VERSION)-ubuntu-ci

  # Ubuntu + Hugo + Onbuild
  ubuntu-onbuild:
    target: ubuntu--onbuild
    platforms:
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
    alias:
      - $(VERSION)-ubuntu-onbuild

tests:
  hugo:
    command: version
    expected: hugo
