name: Ubuntu (standard)

images:
  # Ubuntu + Hugo
  ubuntu:
    target: ubuntu
    alias:
      - $(VERSION)-ubuntu
    tests:
      - hugo

  # Ubuntu + Hugo + CI
  ubuntu-ci:
    target: ubuntu--ci
    alias:
      - $(VERSION)-ubuntu-ci

  # Ubuntu + Hugo + Onbuild
  ubuntu-onbuild:
    target: ubuntu--onbuild
    alias:
      - $(VERSION)-ubuntu-onbuild

tests:
  hugo:
    command: version
    expected: Hugo
